# Generated by Django 6.0.3 on 2026-03-13 06:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_id', models.CharField(db_index=True, max_length=30)),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('youtube_url', models.URLField(blank=True)),
                ('transcript_text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('key_decisions', models.JSONField(default=list)),
                ('participants_detected', models.JSONField(default=list)),
                ('visual_frames', models.JSONField(default=list)),
                ('word_count', models.IntegerField(default=0)),
                ('is_processed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ['-created_at'],
                'unique_together': {('video_id', 'session_key')},
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('initials', models.CharField(blank=True, default='', max_length=5)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('role', models.CharField(choices=[('organizer', 'Organizer'), ('presenter', 'Presenter'), ('attendee', 'Attendee')], default='attendee', max_length=20)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'ordering': ['name'],
                'unique_together': {('meeting', 'email')},
            },
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('assignee_name', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done')], default='pending', max_length=15)),
                ('due_date', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp_reference', models.CharField(blank=True, default='', max_length=10)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='meetings.meeting')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_action_items', to='meetings.participant')),
            ],
            options={
                'verbose_name': 'Action Item',
                'verbose_name_plural': 'Action Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='meetings.meeting')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcript_entries', to='meetings.participant')),
            ],
            options={
                'verbose_name': 'Transcript Entry',
                'verbose_name_plural': 'Transcript Entries',
                'ordering': ['order', 'timestamp'],
            },
        ),
    ]
