# Generated by Django 6.0.3 on 2026-03-10 12:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration of the meeting in minutes')),
                ('video_url', models.URLField(blank=True, default='')),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('initials', models.CharField(blank=True, default='', help_text="Display initials, e.g. 'SJ' for Sarah Jenkins", max_length=5)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('role', models.CharField(choices=[('organizer', 'Organizer'), ('presenter', 'Presenter'), ('attendee', 'Attendee')], default='attendee', max_length=20)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'ordering': ['name'],
                'unique_together': {('meeting', 'email')},
            },
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True, default='', help_text="Additional context, e.g. 'Mentioned at 14:20 during infrastructure discussion'")),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done')], default='pending', max_length=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('timestamp_reference', models.CharField(blank=True, default='', help_text='Timestamp in the video where this action item was mentioned', max_length=10)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='meetings.meeting')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_action_items', to='meetings.participant')),
            ],
            options={
                'verbose_name': 'Action Item',
                'verbose_name_plural': 'Action Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.CharField(help_text="Timestamp in the video, e.g. '12:04'", max_length=10)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this entry in the transcript')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='meetings.meeting')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcript_entries', to='meetings.participant')),
            ],
            options={
                'verbose_name': 'Transcript Entry',
                'verbose_name_plural': 'Transcript Entries',
                'ordering': ['order', 'timestamp'],
            },
        ),
    ]
